name: Docker image build and publish
on:
  push:
    branches:
      - dev

jobs:
  build-push:
    name: Build and publish container

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/${{ secrets.AWS_ROLE }}
          role-session-name: updateimage
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public



      - name: Build, tag, and push API docker image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: "dewberry"
          REPOSITORY: "ras-stac"
          IMAGE_TAG: ${{ github.sha }}
        run: |
        
          docker build . -t "$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG"
          docker push "$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG"
          docker tag "$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG" "$ECR_REGISTRY/$ECR_REPOSITORY:latest"
          docker push "$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest"

          echo "IMAGE $IMAGE_TAG is pushed to $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY"
          echo "$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG overwrote $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest"
